name: Build .NET Solution

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
      - 'bug/*'
      - 'hotfix/*'

jobs:
  build:
    name : Restore Nuget
    runs-on: windows-latest
    steps:
      - name: Restore Dependencies and Build Solution
        run: |
          dotnet restore /FakeApp.sln
          dotnet build /FakeApp.sln --configuration Release
