name: Build .NET Solution

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
      - 'bug/*'
      - 'hotfix/*'

jobs:
  build-and-deploy:
    name: Build and Generate Artifact
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Dependencies
        run: |
          dotnet restore FakeApp.sln
          
      - name: Build Solution
        run: |
          dotnet build FakeApp.sln --configuration Release

      - name: Publish Artifact
        run: |
          dotnet publish FakeApp.sln -c Release -o ./publish

          # Get current date in YYYYMMDD format
          - name: Get Current Date
            id: current_date
            run: echo "::set-output name=date::$(date +'%Y%m%d')"

          # Define custom version identifier (e.g., 'v1')
          - name: Set Version Identifier
            id: version_identifier
            run: echo "::set-output name=version::v1"

          # Combine date and version identifier to create version
          - name: Generate Version
            id: generated_version
            run: echo "::set-output name=generated_version::${{ steps.current_date.outputs.date }}-${{ steps.version_identifier.outputs.version }}"

          # Archive artifact with the generated version
          - name: Archive Artifact
            uses: actions/upload-artifact@v2
            with:
              name: FakeApp-Artifact-${{ steps.generated_version.outputs.generated_version }}
              path: ./publish

  show-artifact:
    name: Show Artifact
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: FakeApp-Artifact-${{ needs.build-and-deploy.outputs.generated_version }}
          path: ./downloaded-artifact

      - name: List Files
        run: ls ./downloaded-artifact

      - name: Provide Artifact Link
        run: |
          echo "Artifact download link: ${{ steps.download-artifact.outputs.artifact_url }}"
