name: Build and Deploy .NET Solution

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
      - 'bug/*'
      - 'hotfix/*'

jobs:
  build-and-deploy:
    name: Build and Generate Artifact
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Read version from file
      - name: Read Version from File
        id: read-version
        run: echo "::set-output name=version::$(cat VERSION.txt)"

      - name: Restore Dependencies
        run: |
          dotnet restore FakeApp.sln
          
      - name: Build Solution
        run: |
          dotnet build FakeApp.sln --configuration Release

      - name: Publish Artifact
        run: |
          dotnet publish FakeApp.sln -c Release -o ./publish/$VERSION

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FakeApp-Artifact-$VERSION
          path: ./publish

  show-artifact:
    name: Show Artifact
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: FakeApp-Artifact-${{ coalesce(needs.build-and-deploy.outputs.version, steps.read-version.outputs.version) }}
          path: ./downloaded-artifact

      - name: List Files
        run: ls ./downloaded-artifact

      - name: Provide Artifact Link
        run: |
          echo "Artifact download link: ${{ steps.download-artifact.outputs.artifact_url }}"
