name: Build .NET Solution

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
      - 'bug/*'
      - 'hotfix/*'

jobs:
  build:
    name: Restore Nuget and Build Solution
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Dependencies and Build Solution
        run: |
          dotnet restore FakeApp.sln
          dotnet build FakeApp.sln --configuration Release
