name: Build Solution

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
      - 'bug/*'
      - 'hotfix/*'

jobs:
  restore-dependencies:
    name: Restore Dependencies 
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Dependencies
        run: |
          dotnet restore FakeApp.sln

  build-solution:
    name: Build Solution 
    runs-on: windows-latest
    needs: restore-dependencies

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Solution
        run: |
          dotnet build FakeApp.sln --configuration Release

  publish-artifact:
    name: Publish Artifact 
    runs-on: windows-latest
    needs: build-solution

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish Artifact
        run: |
          dotnet publish FakeApp.sln -c Release -o ./publish

          - name: Get Timestamp
            id: timestamp
            run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

          - name: Archive Artifact
            uses: actions/upload-artifact@v2
            with:
              name: FakeApp-Artifact-${{ steps.timestamp.outputs.timestamp }}
              path: ./publish

  show-artifact:
    name: Show Artifact
    runs-on: windows-latest
    needs: publish-artifact

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: FakeApp-Artifact-${{ needs.publish-artifact.outputs.timestamp }}
          path: ./downloaded-artifact

      - name: List Files
        run: ls ./downloaded-artifact

      - name: Provide Artifact Link
        run: |
          echo "Artifact download link: ${{ steps.download-artifact.outputs.artifact_url }}"
